dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: knative-go-project
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: opentest-consumer-movies
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: opentest-movies-go
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.130
