dependencies:
- name: discover-movies-go
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: opentest-movies-go
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: opentest-spring-java
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: test-camel
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
